apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: tyixu55pw-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/tyixu55pw-java-springboot-gitops